import type { MuscuZone, Projet } from "@/lib/muscu/types";

export type Zone = MuscuZone;
export type ItemType = "Exercice" | "Étirement" | "Technique" | "Séance";

export type ExerciseTags = {
  zone?: Zone;
  type?: ItemType;
  projets?: Projet[];
  themes?: string[];
};

export const exerciseTagsByCode: Record<string, ExerciseTags> = {
  "S1-01": { zone: "Abdos", type: "Exercice" },
  "S1-02": { zone: "Abdos", type: "Exercice" },
  "S1-03": { zone: "Abdos", type: "Exercice" },
  "S1-04": { zone: "Abdos", type: "Exercice" },
  "S1-05": { zone: "Abdos", type: "Exercice" },
  "S1-06": { zone: "Abdos", type: "Exercice" },
  "S1-07": { zone: "Abdos", type: "Exercice" },
  "S1-08": { zone: "Abdos", type: "Exercice" },
  "S1-09": { zone: "Abdos", type: "Exercice" },
  "S1-10": { zone: "Abdos", type: "Exercice" },
  "S2-01": { zone: "Abdos", type: "Exercice" },
  "S2-02": { zone: "Abdos", type: "Exercice" },
  "S2-03": { zone: "Abdos", type: "Exercice" },
  "S2-04": { zone: "Abdos", type: "Exercice" },
  "S2-05": { zone: "Abdos", type: "Exercice" },
  "S2-06": { zone: "Abdos", type: "Exercice" },
  "S2-07": { zone: "Abdos", type: "Exercice" },
  "S2-08": { zone: "Abdos", type: "Exercice" },
  "S2-09": { zone: "Abdos", type: "Exercice" },
  "S2-10": { zone: "Abdos", type: "Exercice" },
  "S2-11": { zone: "Abdos", type: "Exercice" },
  "S2-12": { zone: "Abdos", type: "Exercice" },
  "S2-13": { zone: "Abdos", type: "Exercice" },
  "S2-14": { zone: "Abdos", type: "Exercice" },
  "S2-15": { zone: "Abdos", type: "Exercice" },
  "S3-01": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-02": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-03": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-04": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-05": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-06": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-07": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-08": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-09": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-10": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-11": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-12": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-13": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-14": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-15": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-16": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-17": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-18": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-19": { zone: "Membres supérieurs", type: "Exercice" },
  "S3-20": { zone: "Membres supérieurs", type: "Exercice" },
  "S4-01": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-02": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-03": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-04": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-05": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-06": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-07": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-08": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-09": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-10": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-11": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-12": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-13": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-14": { zone: "Membres inférieurs", type: "Exercice" },
  "S4-15": { zone: "Membres inférieurs", type: "Exercice" },
  "S5-01": { zone: "Crosstraining", type: "Exercice" },
  "S5-02": { zone: "Crosstraining", type: "Exercice" },
  "S5-03": { zone: "Crosstraining", type: "Exercice" },
  "S5-04": { zone: "Crosstraining", type: "Exercice" },
  "S5-05": { zone: "Crosstraining", type: "Exercice" },
  "S5-06": { zone: "Crosstraining", type: "Exercice" },
  "S5-07": { zone: "Crosstraining", type: "Exercice" },
  "S5-08": { zone: "Crosstraining", type: "Exercice" },
  "S5-09": { zone: "Crosstraining", type: "Exercice" },
  "S5-10": { zone: "Crosstraining", type: "Exercice" },
};
