import type { Exercise } from "@/lib/v3/types";

const baseParams: Exercise["paramsByTheme"] = {
  PUISSANCE: {
    setsRange: [4, 6],
    repsRange: [3, 5],
    restSecRange: [180, 240],
    intensityHint: "RPE 8-9, exécution explosive",
  },
  ENDURANCE_FORCE: {
    setsRange: [2, 4],
    repsRange: [12, 20],
    restSecRange: [45, 90],
    intensityHint: "RPE 6-7, rythme régulier",
  },
  VOLUME: {
    setsRange: [3, 5],
    repsRange: [8, 12],
    restSecRange: [60, 120],
    intensityHint: "RPE 7-8, contrôle technique",
  },
};

export const exercisesSeed: Exercise[] = [
  {
    id: "squat-barre",
    name: "Squat barre",
    muscles: ["Quadriceps", "Fessiers", "Gainage"],
    equipment: ["BARRE"],
    difficulty: 4,
    compatibleThemes: ["PUISSANCE", "VOLUME"],
    technique: {
      cues: [
        "Pieds largeur épaules, talons ancrés",
        "Descente contrôlée, poitrine ouverte",
        "Pousser le sol en remontant",
      ],
      safety: [
        "Dos neutre, gainage actif",
        "Amplitude adaptée à la mobilité",
      ],
      commonMistakes: [
        "Genoux qui rentrent",
        "Buste qui bascule vers l’avant",
      ],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "developpe-couche",
    name: "Développé couché",
    muscles: ["Pectoraux", "Triceps", "Épaules"],
    equipment: ["BARRE"],
    difficulty: 4,
    compatibleThemes: ["PUISSANCE", "VOLUME"],
    technique: {
      cues: [
        "Omoplates serrées sur le banc",
        "Barre descend au bas des pectoraux",
        "Poussée verticale et contrôlée",
      ],
      safety: [
        "Poignets alignés",
        "Spotter recommandé en lourd",
      ],
      commonMistakes: [
        "Épaules décollées",
        "Barre rebondit sur la poitrine",
      ],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "souleve-terre",
    name: "Soulevé de terre",
    muscles: ["Ischios", "Fessiers", "Dos"],
    equipment: ["BARRE"],
    difficulty: 5,
    compatibleThemes: ["PUISSANCE"],
    technique: {
      cues: [
        "Barre proche des tibias",
        "Hanches et épaules montent ensemble",
        "Pousser fort dans le sol",
      ],
      safety: ["Dos plat, regard fixe", "Pas d’à-coups en tirage"],
      commonMistakes: ["Dos rond", "Barre trop éloignée du corps"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "tractions-explosives",
    name: "Tractions explosives",
    muscles: ["Dorsaux", "Biceps", "Avant-bras"],
    equipment: ["BARRE"],
    difficulty: 4,
    compatibleThemes: ["PUISSANCE"],
    technique: {
      cues: [
        "Prise ferme, gainage total",
        "Tirer vite vers le haut",
        "Contrôle en descente",
      ],
      safety: ["Éviter les balancements excessifs"],
      commonMistakes: ["Élan trop important", "Amplitude incomplète"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "saut-vertical",
    name: "Saut vertical",
    muscles: ["Quadriceps", "Mollets", "Fessiers"],
    equipment: ["AUCUN"],
    difficulty: 3,
    compatibleThemes: ["PUISSANCE"],
    technique: {
      cues: [
        "Pré-charge rapide des jambes",
        "Bras actifs pour l’impulsion",
        "Réception souple sur l’avant-pied",
      ],
      safety: ["Genoux alignés à la réception"],
      commonMistakes: ["Réception bruyante", "Genoux qui rentrent"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "push-press",
    name: "Push press",
    muscles: ["Épaules", "Triceps", "Gainage"],
    equipment: ["BARRE"],
    difficulty: 4,
    compatibleThemes: ["PUISSANCE"],
    technique: {
      cues: [
        "Dip court et explosif",
        "Poussée verticale",
        "Verrouillage au-dessus de la tête",
      ],
      safety: ["Ceinture scapulaire active"],
      commonMistakes: ["Dos cambré", "Dip trop profond"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "pompes",
    name: "Pompes",
    muscles: ["Pectoraux", "Triceps", "Gainage"],
    equipment: ["AUCUN"],
    difficulty: 2,
    compatibleThemes: ["ENDURANCE_FORCE", "VOLUME"],
    technique: {
      cues: [
        "Corps gainé, ligne droite",
        "Coudes à 45°",
        "Amplitude contrôlée",
      ],
      safety: ["Nuque alignée", "Mains sous les épaules"],
      commonMistakes: ["Bassin qui s’affaisse", "Amplitude partielle"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "fentes-marchees",
    name: "Fentes marchées",
    muscles: ["Quadriceps", "Fessiers"],
    equipment: ["HALTERES"],
    difficulty: 3,
    compatibleThemes: ["ENDURANCE_FORCE", "VOLUME"],
    technique: {
      cues: [
        "Pas long, buste vertical",
        "Genou arrière proche du sol",
        "Poussée sur le talon avant",
      ],
      safety: ["Genou avant stable"],
      commonMistakes: ["Pas trop court", "Buste qui penche"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "planche",
    name: "Planche",
    muscles: ["Gainage", "Épaules"],
    equipment: ["AUCUN"],
    difficulty: 2,
    compatibleThemes: ["ENDURANCE_FORCE"],
    technique: {
      cues: ["Coudes sous les épaules", "Bassin neutre", "Respiration calme"],
      safety: ["Éviter l’hyperlordose"],
      commonMistakes: ["Hanches trop hautes", "Épaules relâchées"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "rowing-halteres",
    name: "Rowing haltères",
    muscles: ["Dorsaux", "Biceps"],
    equipment: ["HALTERES"],
    difficulty: 3,
    compatibleThemes: ["ENDURANCE_FORCE", "VOLUME"],
    technique: {
      cues: ["Dos plat, buste gainé", "Tirer le coude vers la hanche"],
      safety: ["Nuque alignée"],
      commonMistakes: ["Dos arrondi", "Élan excessif"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "squat-pdc",
    name: "Squat poids du corps",
    muscles: ["Quadriceps", "Fessiers"],
    equipment: ["AUCUN"],
    difficulty: 2,
    compatibleThemes: ["ENDURANCE_FORCE"],
    technique: {
      cues: ["Talons au sol", "Hanches en arrière", "Genoux suivent les pointes"],
      safety: ["Amplitude contrôlée"],
      commonMistakes: ["Talons décollés", "Genoux qui rentrent"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "mountain-climbers",
    name: "Mountain climbers",
    muscles: ["Gainage", "Hanche", "Épaules"],
    equipment: ["AUCUN"],
    difficulty: 2,
    compatibleThemes: ["ENDURANCE_FORCE"],
    technique: {
      cues: ["Épaules au-dessus des mains", "Genoux alternés rapides"],
      safety: ["Dos plat"],
      commonMistakes: ["Bassin qui monte", "Rythme irrégulier"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "presse-cuisses",
    name: "Presse à cuisses",
    muscles: ["Quadriceps", "Fessiers"],
    equipment: ["MACHINES"],
    difficulty: 3,
    compatibleThemes: ["VOLUME"],
    technique: {
      cues: ["Pieds largeur d’épaules", "Descente contrôlée", "Poussée sur les talons"],
      safety: ["Bas du dos en contact avec le dossier"],
      commonMistakes: ["Amplitude trop courte", "Genoux verrouillés"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "hip-thrust",
    name: "Hip thrust",
    muscles: ["Fessiers", "Ischios"],
    equipment: ["BARRE"],
    difficulty: 3,
    compatibleThemes: ["VOLUME"],
    technique: {
      cues: ["Banc au niveau des omoplates", "Poussée des hanches vers le haut"],
      safety: ["Nuque neutre", "Pieds stables"],
      commonMistakes: ["Amplitude incomplète", "Bas du dos hypercambré"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "developpe-incline",
    name: "Développé incliné haltères",
    muscles: ["Pectoraux", "Épaules", "Triceps"],
    equipment: ["HALTERES"],
    difficulty: 3,
    compatibleThemes: ["VOLUME"],
    technique: {
      cues: ["Trajectoire contrôlée", "Poignets alignés"],
      safety: ["Banc stable"],
      commonMistakes: ["Amplitude trop courte", "Coudes trop ouverts"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "tirage-horizontal",
    name: "Tirage horizontal",
    muscles: ["Dos", "Biceps"],
    equipment: ["MACHINES"],
    difficulty: 3,
    compatibleThemes: ["VOLUME"],
    technique: {
      cues: ["Tirer vers le nombril", "Poitrine ouverte"],
      safety: ["Éviter de tirer avec le bas du dos"],
      commonMistakes: ["Épaules qui montent", "Tirage trop rapide"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "leg-curl",
    name: "Leg curl",
    muscles: ["Ischios"],
    equipment: ["MACHINES"],
    difficulty: 2,
    compatibleThemes: ["VOLUME"],
    technique: {
      cues: ["Aligner genou et axe", "Contrôler la descente"],
      safety: ["Pas d’élan"],
      commonMistakes: ["Bassin qui bouge", "Amplitude réduite"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
  {
    id: "elevations-laterales",
    name: "Élévations latérales",
    muscles: ["Épaules"],
    equipment: ["HALTERES"],
    difficulty: 2,
    compatibleThemes: ["VOLUME"],
    technique: {
      cues: ["Bras légèrement fléchis", "Lever jusqu’à l’horizontale"],
      safety: ["Éviter la rotation excessive"],
      commonMistakes: ["Élan avec le buste", "Hauteur trop haute"],
    },
    media: {},
    paramsByTheme: baseParams,
  },
];
