import path from "node:path";
import { getAllExercisesRaw } from "../src/lib/exercises/index";
import {
  UI_TEXT_FIELDS,
  findCrossReferenceCandidates,
} from "../src/lib/exercises/crossRefs";

type Finding = {
  code: string;
  field: string;
  excerpt: string;
  references: string[];
};

const compactExcerpt = (value: string) =>
  value.replace(/\s+/g, " ").trim().slice(0, 160);

const findings: Finding[] = [];

for (const exercise of getAllExercisesRaw()) {
  const code = exercise.code;
  for (const field of UI_TEXT_FIELDS) {
    const value = exercise[field.key];
    if (field.kind === "string") {
      if (typeof value !== "string" || !value.trim()) continue;
      const { codes, hasMarker } = findCrossReferenceCandidates(value, code);
      if (!codes.length && !hasMarker) continue;
      findings.push({
        code,
        field: String(field.key),
        excerpt: compactExcerpt(value),
        references: codes.length ? codes : ["(marker without code)"],
      });
    } else if (Array.isArray(value)) {
      value.forEach((item, index) => {
        if (!item || !item.trim()) return;
        const { codes, hasMarker } = findCrossReferenceCandidates(item, code);
        if (!codes.length && !hasMarker) return;
        findings.push({
          code,
          field: `${String(field.key)}[${index}]`,
          excerpt: compactExcerpt(item),
          references: codes.length ? codes : ["(marker without code)"],
        });
      });
    }
  }
}

if (!findings.length) {
  console.log("Cross-reference audit: 0 findings.");
  process.exit(0);
}

console.log(`Cross-reference audit: ${findings.length} findings.`);
findings.forEach((finding) => {
  const refs = finding.references.join(", ");
  console.log(
    `- ${finding.code} ${finding.field} -> ${refs}\n  ${finding.excerpt}`
  );
});

console.log(
  `\nReport generated by ${path.relative(process.cwd(), __filename)}`
);
