/* This file is auto-generated by scripts/audit-exercises.ts. Do not edit manually. */

export type ExerciseManifestEntry = {
  code: string;
  sessionId: "S1" | "S2" | "S3" | "S4" | "S5";
  sessionNum: number;
  image: string | null;
  hasData: boolean;
  hasAsset: boolean;
};

export const exercisesManifest: ExerciseManifestEntry[] = [
  {
    "code": "S1-01",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-01.webp",
    "hasData": true,
    "hasAsset": true
  },
  {
    "code": "S1-02",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-02.webp",
    "hasData": true,
    "hasAsset": true
  },
  {
    "code": "S1-03",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-03.webp",
    "hasData": true,
    "hasAsset": true
  },
  {
    "code": "S1-04",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-04.webp",
    "hasData": true,
    "hasAsset": true
  },
  {
    "code": "S1-05",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-05.webp",
    "hasData": true,
    "hasAsset": true
  },
  {
    "code": "S1-06",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-06.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S1-07",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-07.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S1-08",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-08.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S1-09",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-09.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S1-10",
    "sessionId": "S1",
    "sessionNum": 1,
    "image": "/exercises/S1/S1-10.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-01",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-01.webp",
    "hasData": true,
    "hasAsset": true
  },
  {
    "code": "S2-02",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-02.webp",
    "hasData": true,
    "hasAsset": true
  },
  {
    "code": "S2-03",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-03.webp",
    "hasData": true,
    "hasAsset": true
  },
  {
    "code": "S2-04",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-04.webp",
    "hasData": true,
    "hasAsset": true
  },
  {
    "code": "S2-05",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-05.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-06",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-06.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-07",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-07.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-08",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-08.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-09",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-09.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-10",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-10.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-11",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-11.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-12",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-12.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-13",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-13.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-14",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-14.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S2-15",
    "sessionId": "S2",
    "sessionNum": 2,
    "image": "/exercises/S2/S2-15.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-01",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-01.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-02",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-02.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-03",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-03.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-04",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-04.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-05",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-05.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-06",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-06.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-07",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-07.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-08",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-08.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-09",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-09.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-10",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-10.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-11",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-11.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-12",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-12.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-13",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-13.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-14",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-14.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-15",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-15.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-16",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-16.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-17",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-17.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-18",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-18.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-19",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-19.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S3-20",
    "sessionId": "S3",
    "sessionNum": 3,
    "image": "/exercises/S3/S3-20.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-01",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-01.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-02",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-02.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-03",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-03.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-04",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-04.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-05",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-05.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-06",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-06.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-07",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-07.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-08",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-08.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-09",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-09.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-10",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-10.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-11",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-11.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-12",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-12.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-13",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-13.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-14",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-14.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S4-15",
    "sessionId": "S4",
    "sessionNum": 4,
    "image": "/exercises/S4/S4-15.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-01",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-01.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-02",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-02.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-03",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-03.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-04",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-04.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-05",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-05.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-06",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-06.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-07",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-07.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-08",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-08.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-09",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-09.webp",
    "hasData": false,
    "hasAsset": true
  },
  {
    "code": "S5-10",
    "sessionId": "S5",
    "sessionNum": 5,
    "image": "/exercises/S5/S5-10.webp",
    "hasData": false,
    "hasAsset": true
  }
];
